typography_spectrum: 0.9299919940531254
content_rating:
  adult: false
color:
  brandColors:
    - '#1d1e18'
    - '#474448'
    - '#d9cfc2'
    - '#ffffff'
    - '#bab9ba'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6121997707523406
analytics:
  google: null
  facebook: null
  twitter: null
name: Carley Moore
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CV
    id: 92b56744-5482-48fe-8cfa-2d654ed7b0f1
    type: content
  - name: Contact
    id: 518d61ca-a42f-4e82-a714-534304a1b498
    type: content
  - name: Monoprint Series
    id: e2a33553-407c-43b0-893c-0d7d7d2390d1
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/70e2cb7a-cc23-4ce3-a8d9-61d17a252efa.png
title: ''
purpose: []
