layout_spectrum: 0.6121997707523406
typography_spectrum: 0.9299919940531254
color:
  brandColors:
    - '#1d1e18'
    - '#474448'
    - '#d9cfc2'
    - '#ffffff'
    - '#bab9ba'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Carley Moore
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CV
    id: 92b56744-5482-48fe-8cfa-2d654ed7b0f1
    type: content
  - name: Contact
    id: 518d61ca-a42f-4e82-a714-534304a1b498
    type: content
favicon: null
purpose: []
