name: Carley Moore
favicon: null
layout_spectrum: 0.8796047314535826
typography_spectrum: 0.73273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7d9bc'
    - '#9c8c77'
    - '#736645'
    - '#254c88'
    - '#791c25'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
