typography_spectrum: 0.537006955826655
color:
  brandColors:
    - '#1d1e18'
    - '#474448'
    - '#d9cfc2'
    - '#ffffff'
    - '#bab9ba'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Carley Moore
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 7ae8137f-9518-483e-9ccc-9e86e04320ec
    type: content
  - name: CV
    id: 92b56744-5482-48fe-8cfa-2d654ed7b0f1
    type: content
favicon: null
purpose: []
