layout_spectrum: 0.48673
typography_spectrum: 0.22784529998898506
color:
  brandColors:
    - '#e7d9bc'
    - '#9c8c77'
    - '#736645'
    - '#254c88'
    - '#791c25'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Carley Moore
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 7ae8137f-9518-483e-9ccc-9e86e04320ec
    type: content
favicon: null
purpose: []
